# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/Desktop/extensibility-routing-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/Desktop/extensibility-routing-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Desktop/extensibility-routing-cpp/CMakeFiles /home/ubuntu/Desktop/extensibility-routing-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Desktop/extensibility-routing-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named solver

# Build rule for target.
solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver
.PHONY : solver

# fast build rule for target.
solver/fast:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/build
.PHONY : solver/fast

extensibility-routing/main.o: extensibility-routing/main.cpp.o

.PHONY : extensibility-routing/main.o

# target to build an object file
extensibility-routing/main.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/main.cpp.o
.PHONY : extensibility-routing/main.cpp.o

extensibility-routing/main.i: extensibility-routing/main.cpp.i

.PHONY : extensibility-routing/main.i

# target to preprocess a source file
extensibility-routing/main.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/main.cpp.i
.PHONY : extensibility-routing/main.cpp.i

extensibility-routing/main.s: extensibility-routing/main.cpp.s

.PHONY : extensibility-routing/main.s

# target to generate assembly for a file
extensibility-routing/main.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/main.cpp.s
.PHONY : extensibility-routing/main.cpp.s

extensibility-routing/src/graph.o: extensibility-routing/src/graph.cpp.o

.PHONY : extensibility-routing/src/graph.o

# target to build an object file
extensibility-routing/src/graph.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/graph.cpp.o
.PHONY : extensibility-routing/src/graph.cpp.o

extensibility-routing/src/graph.i: extensibility-routing/src/graph.cpp.i

.PHONY : extensibility-routing/src/graph.i

# target to preprocess a source file
extensibility-routing/src/graph.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/graph.cpp.i
.PHONY : extensibility-routing/src/graph.cpp.i

extensibility-routing/src/graph.s: extensibility-routing/src/graph.cpp.s

.PHONY : extensibility-routing/src/graph.s

# target to generate assembly for a file
extensibility-routing/src/graph.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/graph.cpp.s
.PHONY : extensibility-routing/src/graph.cpp.s

extensibility-routing/src/johnson.o: extensibility-routing/src/johnson.cpp.o

.PHONY : extensibility-routing/src/johnson.o

# target to build an object file
extensibility-routing/src/johnson.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/johnson.cpp.o
.PHONY : extensibility-routing/src/johnson.cpp.o

extensibility-routing/src/johnson.i: extensibility-routing/src/johnson.cpp.i

.PHONY : extensibility-routing/src/johnson.i

# target to preprocess a source file
extensibility-routing/src/johnson.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/johnson.cpp.i
.PHONY : extensibility-routing/src/johnson.cpp.i

extensibility-routing/src/johnson.s: extensibility-routing/src/johnson.cpp.s

.PHONY : extensibility-routing/src/johnson.s

# target to generate assembly for a file
extensibility-routing/src/johnson.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/johnson.cpp.s
.PHONY : extensibility-routing/src/johnson.cpp.s

extensibility-routing/src/scenario.o: extensibility-routing/src/scenario.cpp.o

.PHONY : extensibility-routing/src/scenario.o

# target to build an object file
extensibility-routing/src/scenario.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/scenario.cpp.o
.PHONY : extensibility-routing/src/scenario.cpp.o

extensibility-routing/src/scenario.i: extensibility-routing/src/scenario.cpp.i

.PHONY : extensibility-routing/src/scenario.i

# target to preprocess a source file
extensibility-routing/src/scenario.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/scenario.cpp.i
.PHONY : extensibility-routing/src/scenario.cpp.i

extensibility-routing/src/scenario.s: extensibility-routing/src/scenario.cpp.s

.PHONY : extensibility-routing/src/scenario.s

# target to generate assembly for a file
extensibility-routing/src/scenario.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/scenario.cpp.s
.PHONY : extensibility-routing/src/scenario.cpp.s

extensibility-routing/src/solution/Enhance_Graph.o: extensibility-routing/src/solution/Enhance_Graph.cpp.o

.PHONY : extensibility-routing/src/solution/Enhance_Graph.o

# target to build an object file
extensibility-routing/src/solution/Enhance_Graph.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Enhance_Graph.cpp.o
.PHONY : extensibility-routing/src/solution/Enhance_Graph.cpp.o

extensibility-routing/src/solution/Enhance_Graph.i: extensibility-routing/src/solution/Enhance_Graph.cpp.i

.PHONY : extensibility-routing/src/solution/Enhance_Graph.i

# target to preprocess a source file
extensibility-routing/src/solution/Enhance_Graph.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Enhance_Graph.cpp.i
.PHONY : extensibility-routing/src/solution/Enhance_Graph.cpp.i

extensibility-routing/src/solution/Enhance_Graph.s: extensibility-routing/src/solution/Enhance_Graph.cpp.s

.PHONY : extensibility-routing/src/solution/Enhance_Graph.s

# target to generate assembly for a file
extensibility-routing/src/solution/Enhance_Graph.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Enhance_Graph.cpp.s
.PHONY : extensibility-routing/src/solution/Enhance_Graph.cpp.s

extensibility-routing/src/solution/ILP.o: extensibility-routing/src/solution/ILP.cpp.o

.PHONY : extensibility-routing/src/solution/ILP.o

# target to build an object file
extensibility-routing/src/solution/ILP.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/ILP.cpp.o
.PHONY : extensibility-routing/src/solution/ILP.cpp.o

extensibility-routing/src/solution/ILP.i: extensibility-routing/src/solution/ILP.cpp.i

.PHONY : extensibility-routing/src/solution/ILP.i

# target to preprocess a source file
extensibility-routing/src/solution/ILP.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/ILP.cpp.i
.PHONY : extensibility-routing/src/solution/ILP.cpp.i

extensibility-routing/src/solution/ILP.s: extensibility-routing/src/solution/ILP.cpp.s

.PHONY : extensibility-routing/src/solution/ILP.s

# target to generate assembly for a file
extensibility-routing/src/solution/ILP.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/ILP.cpp.s
.PHONY : extensibility-routing/src/solution/ILP.cpp.s

extensibility-routing/src/solution/Type1.o: extensibility-routing/src/solution/Type1.cpp.o

.PHONY : extensibility-routing/src/solution/Type1.o

# target to build an object file
extensibility-routing/src/solution/Type1.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Type1.cpp.o
.PHONY : extensibility-routing/src/solution/Type1.cpp.o

extensibility-routing/src/solution/Type1.i: extensibility-routing/src/solution/Type1.cpp.i

.PHONY : extensibility-routing/src/solution/Type1.i

# target to preprocess a source file
extensibility-routing/src/solution/Type1.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Type1.cpp.i
.PHONY : extensibility-routing/src/solution/Type1.cpp.i

extensibility-routing/src/solution/Type1.s: extensibility-routing/src/solution/Type1.cpp.s

.PHONY : extensibility-routing/src/solution/Type1.s

# target to generate assembly for a file
extensibility-routing/src/solution/Type1.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Type1.cpp.s
.PHONY : extensibility-routing/src/solution/Type1.cpp.s

extensibility-routing/src/solution/Type2.o: extensibility-routing/src/solution/Type2.cpp.o

.PHONY : extensibility-routing/src/solution/Type2.o

# target to build an object file
extensibility-routing/src/solution/Type2.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Type2.cpp.o
.PHONY : extensibility-routing/src/solution/Type2.cpp.o

extensibility-routing/src/solution/Type2.i: extensibility-routing/src/solution/Type2.cpp.i

.PHONY : extensibility-routing/src/solution/Type2.i

# target to preprocess a source file
extensibility-routing/src/solution/Type2.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Type2.cpp.i
.PHONY : extensibility-routing/src/solution/Type2.cpp.i

extensibility-routing/src/solution/Type2.s: extensibility-routing/src/solution/Type2.cpp.s

.PHONY : extensibility-routing/src/solution/Type2.s

# target to generate assembly for a file
extensibility-routing/src/solution/Type2.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/Type2.cpp.s
.PHONY : extensibility-routing/src/solution/Type2.cpp.s

extensibility-routing/src/solution/util.o: extensibility-routing/src/solution/util.cpp.o

.PHONY : extensibility-routing/src/solution/util.o

# target to build an object file
extensibility-routing/src/solution/util.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/util.cpp.o
.PHONY : extensibility-routing/src/solution/util.cpp.o

extensibility-routing/src/solution/util.i: extensibility-routing/src/solution/util.cpp.i

.PHONY : extensibility-routing/src/solution/util.i

# target to preprocess a source file
extensibility-routing/src/solution/util.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/util.cpp.i
.PHONY : extensibility-routing/src/solution/util.cpp.i

extensibility-routing/src/solution/util.s: extensibility-routing/src/solution/util.cpp.s

.PHONY : extensibility-routing/src/solution/util.s

# target to generate assembly for a file
extensibility-routing/src/solution/util.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/extensibility-routing/src/solution/util.cpp.s
.PHONY : extensibility-routing/src/solution/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... solver"
	@echo "... extensibility-routing/main.o"
	@echo "... extensibility-routing/main.i"
	@echo "... extensibility-routing/main.s"
	@echo "... extensibility-routing/src/graph.o"
	@echo "... extensibility-routing/src/graph.i"
	@echo "... extensibility-routing/src/graph.s"
	@echo "... extensibility-routing/src/johnson.o"
	@echo "... extensibility-routing/src/johnson.i"
	@echo "... extensibility-routing/src/johnson.s"
	@echo "... extensibility-routing/src/scenario.o"
	@echo "... extensibility-routing/src/scenario.i"
	@echo "... extensibility-routing/src/scenario.s"
	@echo "... extensibility-routing/src/solution/Enhance_Graph.o"
	@echo "... extensibility-routing/src/solution/Enhance_Graph.i"
	@echo "... extensibility-routing/src/solution/Enhance_Graph.s"
	@echo "... extensibility-routing/src/solution/ILP.o"
	@echo "... extensibility-routing/src/solution/ILP.i"
	@echo "... extensibility-routing/src/solution/ILP.s"
	@echo "... extensibility-routing/src/solution/Type1.o"
	@echo "... extensibility-routing/src/solution/Type1.i"
	@echo "... extensibility-routing/src/solution/Type1.s"
	@echo "... extensibility-routing/src/solution/Type2.o"
	@echo "... extensibility-routing/src/solution/Type2.i"
	@echo "... extensibility-routing/src/solution/Type2.s"
	@echo "... extensibility-routing/src/solution/util.o"
	@echo "... extensibility-routing/src/solution/util.i"
	@echo "... extensibility-routing/src/solution/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

